#import "../VenueLink/index.gql"

fragment EventsEventInfo on Event {
  venue {
    ...EventsVenueLink
    name
    ageRestriction
  }
  afterpartyVenue {
    ...EventsVenueLink
    name
    ageRestriction
  }
  doorsAt
  startsAt
}
