#import "../Events/EventInfo/index.gql"
#import "../Events/AfterpartyInfo/index.gql"
#import "../Events/CtaButton/index.gql"

fragment HeroTextUpcoming on Event {
  ...EventsEventInfo
  ...EventsAfterpartyInfo
  ...EventsCtaButton
  title
}
