fragment UtilsEventLifecycle on Event {
  regularOnSale
  earlybirdOnSale
  doorsAt
  startsAt
  endsAt
  submissionsOpen
  submissionsClose
  earlybirdPrice
  regularPrice
  soldOut
  ticketsAtDoor
}
