#import "../../utils/eventStatus.gql"

fragment Announcement on Query {
  announcements: announcementCollection(where: { text_exists: true }, order: sys_publishedAt_DESC, limit: 1) {
    items {
      text
      link
      type
    }
  }

  announcementUpcomingEvents: eventCollection(where: { type: "main event", endsAt_gt: $now }, limit: 1) {
    items {
      title
      link
      startsAt
      ...UtilsEventLifecycle
    }
  }
}
